---
title: "03-run_eval_logreg"
output:
  html_document:
    toc: true
    number_sections: true
---

```{r setup, include=FALSE, echo=F}

library(caret)
library(DescTools)
library(ggplot2)
library(labelled)
library(tidyverse)


knitr::opts_chunk$set(echo = TRUE)
options(box.path = here::here())
box::use(r / load_data)
```

# Data

```{r}
ess <- load_data$ess1()
df <- load_data$preprocess(ess)
data <- load_data$train_test_split(df)
```


```{r}
form <- as.formula(
  "reject_bin ~ gender +
  age +
  relig +
  educ +
  income +
  s_dim_conservation +
  s_dim_transcendence +
  left_right +
  country"
)

model <- glm(form, family = binomial(link = "logit"), data = data$train)

summary(model)
```

```{r}
PseudoR2(model, which = c("McFadden", "McFaddenAdj", "McKelveyZavoina", "Nagelkerke"))
```

```{r}
pred <- predict(model, data$test, type = "response")
y_test <- as_factor(ifelse(pred > .5, 1, 0))
y_true <- data$test$reject_bin
confusionMatrix(y_true, y_test)
```

```{r}
MLmetrics::Recall(y_true = y_true, y_pred = y_test)
MLmetrics::Precision(y_true = y_true, y_pred = y_test)
MLmetrics::F1_Score(y_true = y_true, y_pred = y_test)
```
